"""Foam knowledge-catalog generator (auto-generated by reading the docs — no manual registration).

Scans docs/ and produces two files:
  - docs/_recent.md     : lists every knowledge document "most-recent first" (context re-orientation entry point)
  - docs/_authority.md  : authority-document registry (collects §8 + status: authoritative)

Recency is decided from signals already embedded in the documents (convention: docs/_knowledge-architecture.md §6):
  ① last-updated date → ② created/first-authored date → ③ filename _YYYYMMDD → ④ git commit date → ⑤ file mtime

Authority/deprecated status is not decided by heuristic text scanning but by parsing
**.claude/CLAUDE.md §8, the content-authority SSOT** (the authority-spec table + Deprecated list),
plus the new-standard `status: authoritative` metadata.
→ Because §8 is the single source, the registry cannot drift from §8.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from datetime import date
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
DOCS = _ROOT / "docs"
CLAUDE_MD = _ROOT / ".claude" / "CLAUDE.md"

# Same noise as the Foam graph exclusion (transient/build artifacts) + the generated files themselves
_EXCLUDE_DIRS = {"handoffs", "word_export", "node_modules"}
_EXCLUDE_DIR_PREFIX = ("_tmp_",)
_GENERATED = {
    "_recent.md",
    "_authority.md",
    "index.md",
    "_field_cascade.md",
}  # exclude hub/generated files

_RE_FILENAME_DATE = re.compile(r"_(\d{4})(\d{2})(\d{2})")
_RE_UPDATED = re.compile(r"(?:Last\s*Updated|Updated)[^\n\d]{0,12}(\d{4}-\d{2}-\d{2})")
_RE_CREATED = re.compile(
    r"(?:First\s*Authored|Created|Authored)[^\n\d]{0,12}(\d{4}-\d{2}-\d{2})"
)
_RE_VERSION = re.compile(r"Current\s*Version[^\nv]{0,12}(v\d+\.\d+(?:\.\d+)?)")
_RE_STATUS_AUTH = re.compile(r"[Ss]tatus[^\n]{0,12}authoritative")
_RE_DOCS_PATH = re.compile(r"docs/([^\s`)\]]+\.md)")


@dataclass
class Doc:
    """Document metadata for one catalog row."""

    rel: str  # path relative to docs/
    domain: str  # top-level folder (= domain)
    rdate: date  # decided recency date
    source: str  # source of that date (updated/created/filename/git/mtime)
    version: str  # version found in the body (empty if none)
    authority: bool  # whether it is an authority document (§8 or status:authoritative, excluding deprecated)
    deprecated: bool  # whether it is in the §8 Deprecated list


def _parse_iso(s: str) -> date | None:
    try:
        return date.fromisoformat(s)
    except ValueError:
        return None


def date_from_filename(name: str) -> date | None:
    """filename _YYYYMMDD pattern → creation date (snapshot document)."""
    m = _RE_FILENAME_DATE.search(name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    except ValueError:
        return None


def date_from_updated(text: str) -> date | None:
    """body 'Last Updated' → most-recent update date (the most trustworthy signal)."""
    m = _RE_UPDATED.search(text)
    return _parse_iso(m.group(1)) if m else None


def date_from_created(text: str) -> date | None:
    """body 'Created'/'First Authored' → creation date."""
    m = _RE_CREATED.search(text)
    return _parse_iso(m.group(1)) if m else None


def has_authority_status(text: str) -> bool:
    """Does the document header (first 800 chars) carry the 'status: authoritative' metadata (new standard)?"""
    return bool(_RE_STATUS_AUTH.search(text[:800]))


def version_of(text: str) -> str:
    """body 'Current Version' vX.Y → string (empty if none)."""
    m = _RE_VERSION.search(text)
    return m.group(1) if m else ""


def _paths_in_lines(region: str, prefix: str) -> set[str]:
    """Extract only the docs/ paths from lines in region that start with a given leading character.

    Authority is restricted to table rows (`|`), deprecated to bullets (`-`).
    → Avoids mistaking an incidental docs/ mention in prose or a blockquote (`>`) for authority/deprecated.
    """
    out: set[str] = set()
    for line in region.splitlines():
        if line.lstrip().startswith(prefix):
            out.update(_RE_DOCS_PATH.findall(line))
    return out


def section8_paths(text: str) -> tuple[set[str], set[str]]:
    """CLAUDE.md §8 text → (set of authority spec rel paths, set of deprecated rel paths).

    Authority = §8 table rows (`|`); deprecated = bullets (`-`) after '**Deprecated'. On overlap, deprecated wins.
    """
    m = re.search(r"##\s*8\..*?(?=\n##\s|\Z)", text, re.DOTALL)
    if not m:
        return set(), set()
    section = m.group(0)
    parts = re.split(r"\*\*Deprecated", section, maxsplit=1)
    authority = _paths_in_lines(parts[0], "|")
    deprecated = _paths_in_lines(parts[1], "-") if len(parts) > 1 else set()
    return authority - deprecated, deprecated


def parse_section8(claude_md: Path = CLAUDE_MD) -> tuple[set[str], set[str]]:
    """Extract §8 authority/deprecated paths from the CLAUDE.md file (empty sets if the file is missing)."""
    try:
        return section8_paths(claude_md.read_text(encoding="utf-8", errors="replace"))
    except OSError:
        return set(), set()


def _git_date(path: Path) -> date | None:
    """git last-commit date (fallback). None on failure."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", path.name],
            cwd=path.parent,
            capture_output=True,
            text=True,
            timeout=10,
        )
        return _parse_iso(out.stdout.strip())
    except Exception:
        return None


def recency(path: Path, text: str) -> tuple[date, str]:
    """Return (recency date, source) using the §6 convention priority order."""
    d = date_from_updated(text)
    if d:
        return d, "updated"
    d = date_from_created(text)
    if d:
        return d, "created"
    d = date_from_filename(path.name)
    if d:
        return d, "filename"
    d = _git_date(path)
    if d:
        return d, "git"
    return date.fromtimestamp(path.stat().st_mtime), "mtime"


def _excluded(path: Path, docs_dir: Path) -> bool:
    if path.name in _GENERATED:
        return True
    for part in path.relative_to(docs_dir).parts[:-1]:
        if part in _EXCLUDE_DIRS or part.startswith(_EXCLUDE_DIR_PREFIX):
            return True
    return False


def collect(docs_dir: Path = DOCS) -> list[Doc]:
    """Gather .md files under docs/ and return a Doc list (excluding noise/generated files)."""
    auth_set, dep_set = parse_section8()
    out: list[Doc] = []
    for path in sorted(docs_dir.rglob("*.md")):
        if _excluded(path, docs_dir):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        rdate, source = recency(path, text)
        rel = path.relative_to(docs_dir).as_posix()
        domain = rel.split("/")[0] if "/" in rel else "(root)"
        deprecated = rel in dep_set
        authority = (not deprecated) and (rel in auth_set or has_authority_status(text))
        out.append(
            Doc(rel, domain, rdate, source, version_of(text), authority, deprecated)
        )
    return out


_BANNER = (
    "<!-- Auto-generated — do not edit directly. Regenerate with `python scripts/foam_catalog.py`. "
    "Convention: _knowledge-architecture.md -->\n"
)


def render_recent(docs: list[Doc]) -> str:
    """Generate the most-recent-first catalog markdown."""
    rows = sorted(docs, key=lambda d: (d.rdate, d.rel), reverse=True)
    lines = [
        _BANNER,
        "# Most-recent-first catalog (context re-orientation entry point)\n",
        f"> {len(rows)} documents total · most-recent first. Date-source priority: updated > created > filename > git > mtime. "
        "⭐ = authority (§8) · 🚫 = deprecated (do not reference in operations)\n",
        "| Date | Source | Domain | Document |",
        "|:---|:---:|:---|:---|",
    ]
    for d in rows:
        flag = " ⭐" if d.authority else (" 🚫" if d.deprecated else "")
        lines.append(
            f"| {d.rdate.isoformat()} | {d.source} | {d.domain} | [{d.rel}]({d.rel}){flag} |"
        )
    return "\n".join(lines) + "\n"


def render_authority(docs: list[Doc]) -> str:
    """Generate the authority-registry markdown (content is owned by §8 — here we only collect)."""
    auth = sorted((d for d in docs if d.authority), key=lambda d: d.rel)
    lines = [
        _BANNER,
        "# Authority registry\n",
        "> Content authority (which spec is the truth) is owned by **§8** of [.claude/CLAUDE.md](../.claude/CLAUDE.md). "
        "The list below auto-collects the §8 authority table + `status: authoritative` metadata (not a hand-maintained list). "
        "Register a new authority document in §8 and it appears here automatically.\n",
        "| Document | Version | Last Updated |",
        "|:---|:---:|:---:|",
    ]
    for d in auth:
        lines.append(
            f"| [{d.rel}]({d.rel}) | {d.version or '—'} | {d.rdate.isoformat()} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    docs = collect()
    (DOCS / "_recent.md").write_text(render_recent(docs), encoding="utf-8")
    (DOCS / "_authority.md").write_text(render_authority(docs), encoding="utf-8")
    n_auth = sum(d.authority for d in docs)
    n_dep = sum(d.deprecated for d in docs)
    print(
        f"Generated: {len(docs)} documents -> _recent.md, _authority.md (authority {n_auth} / deprecated {n_dep})"
    )


if __name__ == "__main__":
    main()
